sudo: false
cache: pip

language: python

python:
  - "3.10"

dist: "focal"

before_install:
  # For tests running git command
  - git config --global user.name "test"
  - git config --global user.email "test.test@test.com"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

# command to run tests
script:
  - git --version
  - coverage run --source odoo_module_migrate setup.py test

after_success:
  - coveralls
